### ISSUE TITLE
skos:broadMatch from Dbpedia not working

### ISSUE THREAD

**Issue by abiUni** [acdh-oeaw/vocabseditor#22]
Hello, 
Congratulations on a great tool!

Unfortunately, it's not possible to add relations from Dbpedia and adding the URL does not work either in the different relation fields (skos:related, ...)

<img width="1099" alt="Screenshot 2021-10-01 at 17 36 52 (2)" src="https://user-images.githubusercontent.com/72650016/135648247-847b39e3-dabc-4dc6-a90b-d75a77259db6.png">

**Comment by csae8092** [comment]
@zxenia fix is deployed; @abiUni could you please check if it now works for you and if so, close the issue
Thank you!!!

**Comment by abiUni** [comment]
Works like a charm, thank you!
