### ISSUE TITLE
Can't find the docker compose

### ISSUE THREAD

**Issue by OzgeOzkaya** [acdh-oeaw/vocabseditor#27]
Hello, 

I try to run the application with docker, I followed the instructions and executed on my side. I would like to check the docker compose file but couldn't find it. Can you help me with that?

**Comment by csae8092** [comment]
Hi, @OzgeOzkaya 
I didn't provide any docker compose but you should be able to start the container as described here
https://github.com/acdh-oeaw/vocabseditor#running-the-image

Anyways I'll check if the steps described in the README are still up to date (which might not be the case ...) and also try to provide some docker-compose ready version.

**Comment by OzgeOzkaya** [comment]
Thank you for the commits!
