### ISSUE TITLE
Issues with Docker Image

### ISSUE THREAD

**Issue by bipsark** [acdh-oeaw/vocabseditor#47]
Hi, Not sure if this is the right forum to ask questions, but I am trying to use docker image with Docker desktop under Win 10 environment with localhost:8020 . Docker container for Vocabseditor running fine. However, it does not show me any webpage. It says    "The page isn't working right now. localhost didn't send any data". Is there any suggestion or help I can get in this regard? Thank you in advance.

**Comment by csae8092** [comment]
sorry for the late response but unfortunately I have no experience in with docker desktop.
