### ISSUE TITLE
Import - skos:exactMatch is ignored

### ISSUE THREAD

**Issue by KlausIllmayer** [acdh-oeaw/vocabseditor#51]
If importing a vocabulary (ttl-format) into vocabseditor that holds concepts with `skos:exactMatch`-relations, these relations are ignored and do not show up in the vocabseditor after successful import.

I've attached a simple example import (needed to add .txt because .ttl is not accepted by GitHub), that demonstrates this problem and I've imported it on our vocabseditor-instance, see the [concept-view](https://vocabseditor.acdh.oeaw.ac.at/vocabs/concepts/22601).

Expected fix: semantic relationships like `skos:exactMatch` should be respected in import (it is possible to add them in the edit view and to export them, so it seems that something goes wrong in the import queue - I didn't checked it other semantic relationships are also concerned).

Test vocabulary: 
[testit_exact.ttl.txt](https://github.com/acdh-oeaw/vocabseditor/files/10041474/testit_exact.ttl.txt)

**Comment by csae8092** [comment]
can confirm that skos:exactMatch is currently ignored; as well as all other relation properties pointing to external concepts, updated the test vocabulary

```ttl
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix vocab: <https://vocabs.acdh.oeaw.ac.at/testit/> .

<https://chronontology.dainst.org/period/vpg0DvwPQxyc> skos:exactMatch vocab:100 .

vocab:100 a skos:Concept ;
    dct:source "ACDH-CH" ;
    skos:exactMatch <https://chronontology.dainst.org/period/vpg0DvwPQxyc> ;
    skos:narrowMatch <http://www.eionet.europa.eu/gemet/concept/3252> ;
    skos:exactMatch <https://d-nb.info/gnd/1197273174> ;
    skos:definition "Level 1 of the test-it"@en ;
    skos:inScheme vocab:testitSchema ;
    skos:prefLabel "Level 1"@en ;
    skos:topConceptOf vocab:testitSchema .

vocab:testitSchema a skos:ConceptScheme ;
    rdfs:label "Test it Thesaurus"@en ;
    dc:creator "Klaus Illmayer" ;
    dc:description "Test if import of exactmatch works"@en ;
    dc:language "en" ;
    dc:publisher "ACDH-CH" ;
    dc:subject "Test" ;
    dc:title "Test-it exactmatch"@en ;
    dct:created "2022-11-18" ;
    owl:versionInfo "1.0" ;
    skos:hasTopConcept vocab:100 .
 ```
