### ISSUE TITLE
Differ between conceptScheme identifier and base-URI

### ISSUE THREAD

**Issue by KlausIllmayer** [acdh-oeaw/vocabseditor#58]
Currently, the identifier of the conceptScheme also acts as base-URI for concepts without legacy id. If you do an export of a conceptScheme it will generate concept-URIs based on the identifier of the conceptScheme and additional the  `/concept[id]` appendix. This is problematic, as the identifier of the conceptScheme must not be the base-URI. There are different approaches in place and they currently do have a direct unwanted effect on the concept-URIs. Sometimes, the conceptScheme has a dedicated URI, e.g. `https://example.com/vocabulary/Scheme` or it has a trailing slash at the end, e.g.  `https://example.com/vocabulary/`. In the current setup this leads to concepts that in the [first case](https://vocabseditor.acdh.oeaw.ac.at/vocabs/scheme/386) have a uri `https://example.com/vocabulary/Scheme/concept1234` and in the [second case](https://vocabseditor.acdh.oeaw.ac.at/vocabs/scheme/3) a URI `https://example.com/vocabulary//concept1234` (two slashes in-between). Both is not expected, instead we like to be able to have a base-URI and additionally the possibility of a dedicated different conceptScheme-URI.

The current workaround is to have the identifier of the conceptScheme as baseURI without a trailing slash, e.g. `https://example.com/vocabulary` and use the legacyId field of the conceptScheme for the identifier of the conceptScheme, e.g. `https://example.com/vocabulary/` or `https://example.com/vocabulary/Scheme`. That is not optimal and you need to be aware about this workaround. Could we think about a different approach, that makes it more clear to users, like a a dedicated field baseURI in the conceptScheme definition, that acts for the generation of all other URIs and an identifier-appendix field for the conceptScheme itself? @csae8092 what is your opinion on this and how is this complicating things?

**Comment by KlausIllmayer** [comment]
Okay, I should have tested my workaround beforehand. It seems that legacyId is ignored in case of conceptScheme - will need to file an issue on this. But this makes the issue more urgent.

**Comment by csae8092** [comment]
for reference https://github.com/acdh-oeaw/vocabseditor/blob/master/vocabs/models.py#L175

**Comment by KlausIllmayer** [comment]
fixed, thanks!
